# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geography-Country-Utils
version:      1.07
version_from: lib/Geography/Country/Utils.pm
installdirs:  site
requires:
    Net::Country:                  0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
